### ISSUE TITLE
[`FW-A-29`] Add the CHANGELOG file to the documentation of the project

### ISSUE THREAD

**Issue by John15321** [PWr-Aerospace/based-board-firmware#28]
Blocked by: https://github.com/Aerospace-ASP/Firmware/issues/26

Part of: [FW-A-29](https://docs.google.com/spreadsheets/d/1D9iWHwoo7Pxa0VTRW-jic1c0xyV2Ns-iBp7wxDun_Xw/edit#gid=0&range=A32)

Make sure that the CHANGELOG file is added to the project's documentation and visible to whoever is reading it

**Comment by jkaszowski** [comment]
Merged in [#35](https://github.com/PWr-Aerospace/based-board-firmware/pull/35)
